### ISSUE TITLE
Add Support for Version 2023.3.*

### ISSUE THREAD

**Issue by enCHineer** [cicchr/intellij-shared-settings#2]
Currently the Plugin is limited to IntelliJ Version 231—232.*
This should be extended to current version 233.*

**Comment by cicchr** [comment]
I've updated the plugin compatibility so it will work with 233.* in 1958fd0. The new version should be available on the marketplace in a couple days once JetBrains validates it

**Comment by enCHineer** [comment]
That was fast!
Thank you a lot!
